### ISSUE TITLE
触控板和摄像头还有电源管理在windows下 通过联想电脑管家关闭后mac 无法开启

### ISSUE THREAD

**Issue by jackxu86** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#11]
触控板和摄像头还有电源管理在windows下 通过联想电脑管家关闭后mac 无法开启，有解决方案嘛，谢谢

F6关闭触控板后在Mac下就启动不了，需要到win下面在开启，摄像头，电源管理同样有这个情况。

**Comment by ShiShuMo** [comment]
这些问题就不要再问了，毕竟黑苹果，做到这种地步已经很不错的，还有，电源管理和摄像头我没有你说的问题，摄像头走的usb通道，应该是你自己弄出来的问题，电源我的很正常，并且我也解了cfg,触摸板不要再问了，你自己在win下关闭mac本来就不能用，这个是驱动的问题，你可以自己写驱动完善或者自己提交驱动补丁给那位大佬，我没有那个能耐。10.15也是有这个问题的，无解

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jackxu86 "<notifications@github.com&gt;;
发送时间：2020年12月30日(星期三) 下午3:18
收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 触控板和摄像头还有电源管理在windows下 通过联想电脑管家关闭后mac 无法开启 (#11)
-----------------------------------

 

 
触控板和摄像头还有电源管理在windows下 通过联想电脑管家关闭后mac 无法开启，有解决方案嘛，谢谢
 
F6关闭触控板后在Mac下就启动不了，需要到win下面在开启，摄像头，电源管理同样有这个情况。

**Comment by jackxu86** [comment]
谢谢老大回复！知悉！
