### ISSUE TITLE
感谢大佬提供博通驱动，昨天换回inter网卡了，大佬有试过隔空和随航嘛！

### ISSUE THREAD

**Issue by jackxu86** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#13]

**Comment by ShiShuMo** [comment]
不用这两个功能，没试，貌似随航不行，隔空部分设备可以

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jackxu86 "<notifications@github.com&gt;;
发送时间：2021年1月16日(星期六) 下午3:03
收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 感谢大佬提供博通驱动，昨天换回inter网卡了，大佬有试过隔空和随航嘛！ (#13)
-----------------------------------

**Comment by jackxu86** [comment]
谢谢大佬，隔空还是挺方便的，传送图片文件啥的，随航没体验过
