### ISSUE TITLE
HDMI输出

### ISSUE THREAD

**Issue by zhaozhicheng1997** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#2]
亲，感谢你对本EFI文件的维护，但是我没有没有HDMI输出呀，亲可以修复下这个问题吗。谢谢啦

**Comment by ShiShuMo** [comment]
麻烦用hackintool查看hdmi接口是哪个，我这里没有用到hdmi外接，把接口索引总线id还有标识符发一下，我尝试修复一下

**Comment by zhaozhicheng1997** [comment]
![image](https://user-images.githubusercontent.com/20034217/94934116-e29b5600-04fd-11eb-99f6-1cf48b048de3.png)

**Comment by zhaozhicheng1997** [comment]
我也不知道是哪里出了问题。我之前用的clover引导， hdmi就可以正常外接输出。现在换成oc引导就不可以了。 搞了一晚上没有结果（其实我也不知道该修改哪里）。麻烦您了，如果不行的话，我就继续换回我的clover引导了。因为感觉不接外屏，电脑太费眼睛了。谢谢啦。

**Comment by zhaozhicheng1997** [comment]
> 麻烦用hackintool查看hdmi接口是哪个，我这里没有用到hdmi外接，把接口索引总线id还有标识符发一下，我尝试修复一下

我也不知道是哪里出了问题。我之前用的clover引导， hdmi就可以正常外接输出。现在换成oc引导就不可以了。 搞了一晚上没有结果（其实我也不知道该修改哪里）。麻烦您了，如果不行的话，我就继续换回我的clover引导了。因为感觉不接外屏，电脑太费眼睛了。谢谢啦。

![](https://user-images.githubusercontent.com/20034217/94934116-e29b5600-04fd-11eb-99f6-1cf48b048de3.png)

**Comment by ShiShuMo** [comment]
你接上hdmi接口那个没有变绿吗，貌似hdmi要关机状态下接上再开机才有，不支持热拔插好像，我也没外屏测试

**Comment by ShiShuMo** [comment]
你试试我刚更新的，然后把机型改成macbook pro 13,1试试

**Comment by zhaozhicheng1997** [comment]
> 你试试我刚更新的，然后把机型改成macbook pro 13,1试试

我刚刚更新了一下，还是不可以。也许是机型不一样吧，我的是拯救者15isk，我主板和cpu都和你的一样，但是外界接口可能不太一样。我已经换回clover了，因为工作要用。   最后，谢谢你的解答与帮助了。
