### ISSUE TITLE
大佬还会更新吗？

### ISSUE THREAD

**Issue by binz160111** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#3]
我电脑配置跟你一样，用这个efi安装15.7能开机，装11开不了机。大佬能帮我看看吗

**Comment by ShiShuMo** [comment]
加个-v参数看看

**Comment by binz160111** [comment]
> 加个-v参数看看

localhost com.apple.xpc.launched卡在这里，无限循环跑码，

**Comment by ShiShuMo** [comment]
不可能啊，那么多人用我这个都成功安装了，要不你用别的大佬的试试，或者禁用一些kext看看？

**Comment by binz160111** [comment]
> 不可能啊，那么多人用我这个都成功安装了，要不你用别的大佬的试试，或者禁用一些kext看看？

哈哈哈，翻遍远景，就你这一个我可以用的，然后我昨天自己参照教程配了个oc6.2的，也是15.7能启动，Big Sur升不了，醉了醉了

**Comment by ShiShuMo** [comment]
能ota没道理安装不了，你检查下你的硬件或者nvram的问题看看，我用这个没任何问题目前，11的睡眠问题也修复了，目前已经没有睡眠唤醒之后关机变重启问题了，所有的缺失ssdt都加上了，试试，你再试试全部用我github上的，你的那个备份看看

**Comment by binz160111** [comment]
> 能ota没道理安装不了，你检查下你的硬件或者nvram的问题看看，我用这个没任何问题目前，11的睡眠问题也修复了，目前已经没有睡眠唤醒之后关机变重启问题了，所有的缺失ssdt都加上了，试试，你再试试全部用我github上的，你的那个备份看看

试过无数次了，还是不行，哈哈哈，硬件的话跟你的几乎都是相通的。我的电脑上acer t5000。升11bios需要做什么改动吗？

**Comment by ShiShuMo** [comment]
你不是小新700，难怪用不了，我打的那么多ssdt补丁，你肯定开不起机啊，bios都不一样，试着把一些无关紧要的ssdt去掉吧

**Comment by ShiShuMo** [comment]
设备树里面把pci删了那些没有用的，只留下显卡和音频的pci再试试，你不是这个机型我也没办法，并不是说硬件配置一样就可以通用的
