### ISSUE TITLE
能不能整一个博通网卡的版本？或者兼容博通网卡

### ISSUE THREAD

**Issue by yz1311** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#4]
RT

**Comment by ShiShuMo** [comment]
抱歉，没用过博通卡，不清楚用什么驱动，你可以参加别人的改下，或者自己添加博通卡的驱动，或者你把相关驱动链接提供给我，我添加进去，我这个是我自用的，目前已经完美升级bigsur beta10

**Comment by yz1311** [comment]
我昨天试了你的EFI，有个问题，你这边写死的windows10和Ubuntu(我并没有安装)，这两个选项我都点击进不去系统，能不能换成动态加载的形式，并不是都安装了三系统

**Comment by ShiShuMo** [comment]
改好了，已上传

**Comment by yz1311** [comment]
改了之后只有一个MacOS选项了....

**Comment by ShiShuMo** [comment]
自己改下不就好了，已更新config

**Comment by yz1311** [comment]
感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:

https://zhaoyang.lanzous.com/ipLYHhmmtbg

**Comment by 1754164240** [comment]
> 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> 
> https://zhaoyang.lanzous.com/ipLYHhmmtbg

改博通版，要改哪些东西啊

**Comment by ShiShuMo** [comment]
你添加了哪些驱动呀，我有空建一个分支吧



---原始邮件---
发件人: "VN_Yang"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 中午12:22
收件人: "ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC"<Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"莫诗书"<admin@52mss.cn&gt;;
主题: Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4)




  
感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
 
https://zhaoyang.lanzous.com/ipLYHhmmtbg
  
改博通版，要改哪些东西啊

**Comment by 1754164240** [comment]
> 你添加了哪些驱动呀，我有空建一个分支吧
> […](#)
> ---原始邮件--- 发件人: "VN_Yang"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 中午12:22 收件人: "ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC"<Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"莫诗书"<admin@52mss.cn&gt;; 主题: Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常: https://zhaoyang.lanzous.com/ipLYHhmmtbg 改博通版，要改哪些东西啊 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

可以的，我看论坛和git这边都有人用的博通卡，我试了他前面改的那版,HDMI输出黑屏，大佬你lntel版本的有这问题吗

**Comment by ShiShuMo** [comment]
我没试过hdmi黑屏不，你用我的试试，没开机的时候就接上，再开机看看



---原始邮件---
发件人: "VN_Yang"<notifications@github.com&gt;
发送时间: 2020年11月24日(周二) 下午2:59
收件人: "ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC"<Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"莫诗书"<admin@52mss.cn&gt;;
主题: Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4)




  
你添加了哪些驱动呀，我有空建一个分支吧
 …
 ---原始邮件--- 发件人: "VN_Yang"<notifications@github.com&gt; 发送时间: 2020年11月24日(周二) 中午12:22 收件人: "ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC"<Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"莫诗书"<admin@52mss.cn&gt;; 主题: Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常: https://zhaoyang.lanzous.com/ipLYHhmmtbg 改博通版，要改哪些东西啊 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以的，我看论坛和git这边都有人用的博通卡，我试了他前面改的那版,HDMI输出黑屏，大佬你lntel版本的有这问题吗

**Comment by jackxu86** [comment]
博通DW1820A 可以吗？能直接上吗？

**Comment by 1754164240** [comment]
> 博通DW1820A 可以吗？能直接上吗？

不行，上面有个老哥上传了博通网卡的版本，你替换下

**Comment by ShiShuMo** [comment]
我没得博通卡啊，还有现在intel驱动已经挺不错了，可以有百兆宽带速度了，不如换回来吧

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jackxu86 "<notifications@github.com&gt;;
发送时间：2021年1月15日(星期五) 下午5:36
收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送："莫诗书 "<admin@52mss.cn&gt;;"State change "<state_change@noreply.github.com&gt;;
主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4)
-----------------------------------

 

 
博通DW1820A 可以吗？能直接上吗？

**Comment by ShiShuMo** [comment]
有空弄下吧，不保证成功，毕竟我没有博通卡

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："VN_Yang "<notifications@github.com&gt;;
发送时间：2021年1月15日(星期五) 下午5:38
收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送："莫诗书 "<admin@52mss.cn&gt;;"State change "<state_change@noreply.github.com&gt;;
主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4)
-----------------------------------

 

  
博通DW1820A 可以吗？能直接上吗？
  
不行，上面有个老哥上传了博通网卡的版本，你替换下

**Comment by jackxu86** [comment]
> 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> 
> https://zhaoyang.lanzous.com/ipLYHhmmtbg

有

> 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> 
> https://zhaoyang.lanzous.com/ipLYHhmmtbg

亲，自己怎么加，可否简单指导，主要是有时候进不了系统，如果进系统可以参考教程加

> > 博通DW1820A 可以吗？能直接上吗？
> 
> 不行，上面有个老哥上传了博通网卡的版本，你替换下

谢谢，他的好像是bcm94352z(dw1560) 我的是bcm94350(dw1820a)，不知道是否通用哟，直接代码加到作者的文件里是否可以呢？

**Comment by jackxu86** [comment]
> 有空弄下吧，不保证成功，毕竟我没有博通卡
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："VN_Yang "<notifications@github.com&gt;; 发送时间：2021年1月15日(星期五) 下午5:38 收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;; 抄送："莫诗书 "<admin@52mss.cn&gt;;"State change "<state_change@noreply.github.com&gt;; 主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) ----------------------------------- 博通DW1820A 可以吗？能直接上吗？ 不行，上面有个老哥上传了博通网卡的版本，你替换下 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

这款网卡，小兵的
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html

**Comment by jackxu86** [comment]
感谢诗书啊！

**Comment by 1754164240** [comment]
> > 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> > https://zhaoyang.lanzous.com/ipLYHhmmtbg
> 
> 有
> 
> > 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> > https://zhaoyang.lanzous.com/ipLYHhmmtbg
> 
> 亲，自己怎么加，可否简单指导，主要是有时候进不了系统，如果进系统可以参考教程加
> 
> > > 博通DW1820A 可以吗？能直接上吗？
> > 
> > 
> > 不行，上面有个老哥上传了博通网卡的版本，你替换下
> 
> 谢谢，他的好像是bcm94352z(dw1560) 我的是bcm94350(dw1820a)，不知道是否通用哟，直接代码加到作者的文件里是否可以呢？

应该是通用的，我是bcm94360cs2，都可以驱动

**Comment by 1754164240** [comment]
> 我没得博通卡啊，还有现在intel驱动已经挺不错了，可以有百兆宽带速度了，不如换回来吧
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："jackxu86 "<notifications@github.com&gt;; 发送时间：2021年1月15日(星期五) 下午5:36 收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;; 抄送："莫诗书 "<admin@52mss.cn&gt;;"State change "<state_change@noreply.github.com&gt;; 主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) ----------------------------------- 博通DW1820A 可以吗？能直接上吗？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，已经换回原生intel网卡了，再次感谢大佬的开源

**Comment by jackxu86** [comment]
> > > 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> > > https://zhaoyang.lanzous.com/ipLYHhmmtbg
> > 
> > 
> > 有
> > > 感谢作者开源，研究了下弄了个博通网卡版(94352Z),蓝牙 wifi均正常:
> > > https://zhaoyang.lanzous.com/ipLYHhmmtbg
> > 
> > 
> > 亲，自己怎么加，可否简单指导，主要是有时候进不了系统，如果进系统可以参考教程加
> > > > 博通DW1820A 可以吗？能直接上吗？
> > > 
> > > 
> > > 不行，上面有个老哥上传了博通网卡的版本，你替换下
> > 
> > 
> > 谢谢，他的好像是bcm94352z(dw1560) 我的是bcm94350(dw1820a)，不知道是否通用哟，直接代码加到作者的文件里是否可以呢？
> 
> 应该是通用的，我是bcm94360cs2，都可以驱动

谢谢，有空试试，原来的inter网卡也在，后买买的博通，现在的OC也正常，有一些小小的问题 。

**Comment by jackxu86** [comment]
> > 我没得博通卡啊，还有现在intel驱动已经挺不错了，可以有百兆宽带速度了，不如换回来吧
> > […](#)
> > ---------- 该邮件从移动设备发送
> > --------------原始邮件-------------- 发件人："jackxu86 "<[notifications@github.com](mailto:notifications@github.com)>; 发送时间：2021年1月15日(星期五) 下午5:36 收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <[Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com](mailto:Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com)>; 抄送："莫诗书 "<[admin@52mss.cn](mailto:admin@52mss.cn)>;"State change "<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) ----------------------------------- 博通DW1820A 可以吗？能直接上吗？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 嗯，已经换回原生intel网卡了，再次感谢大佬的开源

inter 可以隔空投送吗？

**Comment by 1754164240** [comment]
> > > 我没得博通卡啊，还有现在intel驱动已经挺不错了，可以有百兆宽带速度了，不如换回来吧
> > > […](#)
> > > ---------- 该邮件从移动设备发送
> > > --------------原始邮件-------------- 发件人："jackxu86 "<[notifications@github.com](mailto:notifications@github.com)>; 发送时间：2021年1月15日(星期五) 下午5:36 收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <[Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com](mailto:Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com)>; 抄送："莫诗书 "<[admin@52mss.cn](mailto:admin@52mss.cn)>;"State change "<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) ----------------------------------- 博通DW1820A 可以吗？能直接上吗？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 嗯，已经换回原生intel网卡了，再次感谢大佬的开源
> 
> inter 可以隔空投送吗？

好像是支持的

**Comment by jackxu86** [comment]
> > > > 我没得博通卡啊，还有现在intel驱动已经挺不错了，可以有百兆宽带速度了，不如换回来吧
> > > > […](#)
> > > > ---------- 该邮件从移动设备发送
> > > > --------------原始邮件-------------- 发件人："jackxu86 "<[notifications@github.com](mailto:notifications@github.com)>; 发送时间：2021年1月15日(星期五) 下午5:36 收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <[Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com](mailto:Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com)>; 抄送："莫诗书 "<[admin@52mss.cn](mailto:admin@52mss.cn)>;"State change "<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>; 主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 能不能整一个博通网卡的版本？或者兼容博通网卡 (#4) ----------------------------------- 博通DW1820A 可以吗？能直接上吗？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 嗯，已经换回原生intel网卡了，再次感谢大佬的开源
> > 
> > 
> > inter 可以隔空投送吗？
> 
> 好像是支持的

谢谢，回头试试

**Comment by jackxu86** [comment]
换回inter了，nice 随航和隔空好像不行哈

**Comment by ShiShuMo** [comment]
改好了，试下吧
