### ISSUE TITLE
usb2.0与蓝牙无法使用

### ISSUE THREAD

**Issue by manjaoe** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#6]
usb2.0端口好像无法使用，蓝牙也不能用

**Comment by ShiShuMo** [comment]
我的和其他人的都可以，你的不行就自己定制吧，蓝牙自己换适合你得网卡的驱动

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："manjaoe "<notifications@github.com&gt;;
发送时间：2020年12月6日(星期天) 中午11:47
收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] usb2.0与蓝牙无法使用 (#6)
-----------------------------------

 

 
usb2.0端口好像无法使用，蓝牙也不能用

**Comment by manjaoe** [comment]
大佬，请教一下，我在定制usb的时候，将鼠标插进usb2.0端口，鼠标不亮，hackintool中的usb接口也没有亮的，怎么解决
