### ISSUE TITLE
触摸板问题

### ISSUE THREAD

**Issue by coressss** [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#9]
请问有没有遇到按F6关闭触摸板后再按F6打不开触摸板的问题，到windows下可以打开

**Comment by oj2002cn** [comment]
刚试了下，我也是这样，关了打不开了。

**Comment by jackxu86** [comment]
同样的问题！！！

**Comment by ShiShuMo** [comment]
触摸板在win下打开才能在黑果用，这个问题问驱动开发者吧，我解决不了，黑苹果的机子没人能解决这个问题，如果你真的在意这个问题，建议上白苹果吧

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jackxu86 "<notifications@github.com&gt;;
发送时间：2020年12月24日(星期四) 中午12:57
收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 触摸板问题 (#9)
-----------------------------------

 

 
同样的问题！！！

**Comment by coressss** [comment]
> 触摸板在win下打开才能在黑果用，这个问题问驱动开发者吧，我解决不了，黑苹果的机子没人能解决这个问题，如果你真的在意这个问题，建议上白苹果吧
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："jackxu86 "<notifications@github.com&gt;; 发送时间：2020年12月24日(星期四) 中午12:57 收件人："ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC" <Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：Re: [ShiShuMo/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC] 触摸板问题 (#9) ----------------------------------- 同样的问题！！！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by coressss** [comment]
从10.13到10.15是可以用F6开关的

**Comment by ShiShuMo** [comment]
.
